import type { ChapterQuiz } from '@/types/quiz';

export const ch18Quiz: ChapterQuiz = {
  chapterId: 'ch18',
  title: 'Sustainable AI Quiz',
  description: 'Test your understanding of AI\'s environmental impact, carbon footprint, energy efficiency, and green AI.',
  passingScore: 70,
  selectCount: 5,
  pool: [
    {
      id: 'ch18-q1',
      question: 'What is the primary environmental concern with large-scale ML training?',
      options: [
        'The noise generated by data center cooling systems',
        'The significant carbon emissions from the energy consumed by GPUs during training, which can equal the lifetime emissions of multiple cars',
        'The physical space occupied by server racks',
        'The water used to manufacture ML chips',
      ],
      correctIndex: 1,
      explanation:
        'Training large models (like GPT-3) can consume hundreds of MWh of electricity, producing carbon emissions comparable to several round-trip transatlantic flights or the lifetime emissions of multiple cars. As models grow, this environmental cost scales significantly.',
      difficulty: 'easy',
    },
    {
      id: 'ch18-q2',
      question: 'What does the concept of "Green AI" advocate?',
      options: [
        'Using green-colored server hardware',
        'Prioritizing computational efficiency alongside accuracy, measuring and reporting the carbon cost of ML research and development',
        'Only training models using renewable energy',
        'Replacing all AI systems with manual processes',
      ],
      correctIndex: 1,
      explanation:
        'Green AI (Schwartz et al., 2020) advocates for making efficiency a first-class research metric alongside accuracy. It encourages reporting computational cost, developing more efficient methods, and considering the environmental impact of scaling decisions.',
      difficulty: 'medium',
    },
    {
      id: 'ch18-q3',
      question: 'How does the choice of data center location affect the carbon footprint of ML training?',
      options: [
        'Location does not affect carbon emissions',
        'The electricity grid mix varies by region — training in regions powered by renewables (hydro, wind, solar) can reduce carbon emissions by 10-100x compared to fossil-fuel-heavy grids',
        'Colder locations always have lower emissions',
        'All data centers use the same energy sources',
      ],
      correctIndex: 1,
      explanation:
        'Carbon intensity per kWh varies dramatically by region: Quebec (hydro-powered) produces ~20g CO2/kWh while some coal-heavy regions exceed 900g CO2/kWh. Scheduling training to renewable-rich regions or times can drastically cut emissions for the same computation.',
      difficulty: 'medium',
    },
    {
      id: 'ch18-q4',
      question: 'What is the relationship between model size and energy consumption?',
      options: [
        'Energy consumption is independent of model size',
        'Larger models require more FLOPs for both training and inference, leading to higher energy consumption, though efficiency techniques can partially offset this growth',
        'Smaller models always consume more energy due to inefficiency',
        'Energy consumption is only determined by hardware, not model size',
      ],
      correctIndex: 1,
      explanation:
        'Model size drives energy consumption through increased FLOPs (more parameters means more computation per training step and inference query). The trend toward larger models has exponentially increased energy demands, motivating research into efficient architectures and training methods.',
      difficulty: 'easy',
    },
    {
      id: 'ch18-q5',
      question: 'What strategies can reduce the carbon footprint of ML training?',
      options: [
        'Only training models during daylight hours',
        'Using efficient architectures, mixed precision training, training in low-carbon regions, and choosing appropriately-sized models for the task',
        'Training for fewer epochs regardless of convergence',
        'Avoiding the use of GPUs entirely',
      ],
      correctIndex: 1,
      explanation:
        'Multiple strategies combine: efficient architectures (less computation), mixed precision (faster training), carbon-aware scheduling (renewable-heavy grids/times), early stopping (no wasted epochs), model reuse (fine-tuning vs. training from scratch), and right-sizing models for the task.',
      difficulty: 'medium',
    },
    {
      id: 'ch18-q6',
      question: 'What is the "compute trend" problem in modern AI research?',
      options: [
        'Compute is becoming cheaper, solving all sustainability concerns',
        'The compute required for state-of-the-art models has been growing exponentially (doubling every few months), far outpacing hardware efficiency gains',
        'Modern AI requires less compute than 10 years ago',
        'The problem is that we have too much compute available',
      ],
      correctIndex: 1,
      explanation:
        'OpenAI showed that compute for the largest training runs has been doubling every 3.4 months since 2012, a rate far exceeding Moore\'s Law. This exponential growth in compute demand, if unchecked, leads to unsustainable energy consumption and carbon emissions.',
      difficulty: 'hard',
    },
    {
      id: 'ch18-q7',
      question: 'Why is inference-time energy often more important than training-time energy from a total carbon perspective?',
      options: [
        'Inference always uses more energy per query than training',
        'While training is a one-time cost, inference runs continuously on millions of requests, and the cumulative inference energy can far exceed training energy over a model\'s lifetime',
        'Inference uses renewable energy while training does not',
        'Training energy is negligible compared to inference',
      ],
      correctIndex: 1,
      explanation:
        'A model is trained once but serves inference requests continuously. For widely deployed models handling millions of daily queries, the cumulative inference energy over the model\'s lifetime can be 10-1000x the training cost, making inference efficiency crucial for sustainability.',
      difficulty: 'hard',
    },
    {
      id: 'ch18-q8',
      question: 'What is the role of carbon-aware computing in sustainable AI?',
      options: [
        'Using carbon fiber cables in data centers',
        'Scheduling ML workloads to run when and where the electricity grid has the lowest carbon intensity, shifting computation to greener times and locations',
        'Computing the amount of carbon in the atmosphere',
        'Only running AI models that study climate change',
      ],
      correctIndex: 1,
      explanation:
        'Carbon-aware computing shifts flexible workloads (like training, which is delay-tolerant) to times when renewable energy is abundant (e.g., sunny/windy periods) and to regions with cleaner grids. This can reduce carbon emissions without changing the model or training procedure.',
      difficulty: 'medium',
    },
    {
      id: 'ch18-q9',
      question: 'How does knowledge distillation contribute to sustainable AI?',
      options: [
        'It does not have any environmental benefit',
        'It transfers the capabilities of large energy-intensive models to smaller efficient ones, reducing the energy needed for inference at deployment scale',
        'It creates knowledge that replaces the need for AI',
        'It recycles old model weights into new models',
      ],
      correctIndex: 1,
      explanation:
        'Knowledge distillation enables deploying compact student models that capture most of the teacher\'s capability. Since inference dominates lifetime energy consumption, replacing a large model with a smaller distilled version can yield enormous cumulative energy savings.',
      difficulty: 'hard',
    },
    {
      id: 'ch18-q10',
      question: 'What is the significance of reporting computational costs in ML publications?',
      options: [
        'It is required by all ML conferences',
        'It enables the community to understand the true cost of results, compare methods fairly on efficiency, and make informed decisions about which approaches are practical',
        'It is only relevant for industry papers, not academic research',
        'It discourages innovation by highlighting costs',
      ],
      correctIndex: 1,
      explanation:
        'Reporting compute (GPU hours, total FLOPs, energy, carbon) promotes transparency and accountability. It reveals whether accuracy gains are due to better methods or simply more compute, helps reproduce results, and encourages the community to value efficiency as a research contribution.',
      difficulty: 'easy',
    },
  ],
};
